import { Inter } from "next/font/google";

import Header from './header'
import Footer from './footer'

import "./globals.css";

//imports MSW
// if (process.env.NEXT_PUBLIC_API_MOCKING === 'true') {
//   import('../mocks').then(({ setupMocks }) => {
//     setupMocks()
//   })
// }

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}